# TODO: For a PR, if only grammars/queries change, compile and test only the affected languages.
trigger:
  branches:
    include:
    - master
    - azure-pipelines               # To test changes related to Azure Pipelines.
    - ci                            # To test all CI changes.
  paths:
    exclude:
    - README.org
    - CHANGELOG.md

pr:
- master

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: emacs-tree-sitter
  - repository: elisp-tree-sitter
    type: github
    name: emacs-tree-sitter/elisp-tree-sitter
    ref: azure-pipelines
    endpoint: emacs-tree-sitter

jobs:
- job: Build
  pool:
    vmImage: $(IMAGE_NAME)
  strategy:
    matrix:
      windows-2019:
        IMAGE_NAME: 'windows-2019'
        BUNDLE_TARGET: windows
      macos-10.15-emacs-27.1:
        IMAGE_NAME: 'macos-10.15'
        EVM_EMACS: emacs-27.1
        BUNDLE_TARGET: macos
      ubuntu-18.04-emacs-27.1:
        IMAGE_NAME: 'ubuntu-18.04'
        EVM_EMACS: emacs-27.1
        BUNDLE_TARGET: linux
  steps:
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-tree-sitter-cli.yml@elisp-tree-sitter
    parameters:
      version: 0.19.3
  - template: steps/grammar-bundle/-create.yml
  - template: steps/grammar-bundle/-test.yml
