trigger:
  tags:
    include:
    - '*.*.*'

pr: none

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: ubolonton
  - repository: emacs-tree-sitter
    type: github
    name: ubolonton/emacs-tree-sitter
    ref: azure-pipelines
    endpoint: ubolonton

jobs:
- job: Build
  pool:
    vmImage: $(IMAGE_NAME)
  strategy:
    matrix:
      vs2017-win2016:
        IMAGE_NAME: 'vs2017-win2016'
        BUNDLE_TARGET: windows
      macos-10.14-emacs-27.1:
        IMAGE_NAME: 'macos-10.14'
        EVM_EMACS: emacs-27.1
        BUNDLE_TARGET: macos
      ubuntu-18.04-emacs-27.1:
        IMAGE_NAME: 'ubuntu-18.04'
        EVM_EMACS: emacs-27.1
        BUNDLE_TARGET: linux
  steps:
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-tree-sitter-cli.yml@emacs-tree-sitter
    parameters:
      version: 0.19.3
  - template: steps/grammar-bundle/-create.yml
  - template: steps/grammar-bundle/-save.yml

- job: Publish
  dependsOn: Build
  pool:
    vmImage: macos-10.14
  variables:
    EVM_EMACS: emacs-26.3
    BUNDLE_VERSION: $[ dependencies.Build.outputs['vs2017-win2016.SetBundleVersion.BUNDLE_VERSION'] ]
  steps:
  - template: steps/grammar-bundle/-load.yml
    parameters:
      targets:
      - windows
      - macos
      - linux
  - template: steps/grammar-bundle/-upload.yml
    parameters:
      endpoint: github.com_ubolonton
